# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #in_memory:
        #    memory: ~
        tautof_db_provider:
            entity:
                class: AppBundle:User
                property: username
    encoders:
       AppBundle\Entity\User: bcrypt


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            #intercept access controls rules by calling this service, see services.yml
            entry_point: security_hook 
            # activate different ways to authenticate

            #http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: login
                check_path: login
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            logout: { path: /logout, target: / }
        
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/advert/new, roles: ROLE_USER }